spring:
  application:
    name: admin-server
  profiles:
    active:
      - secure

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health ，2.0后actuator的地址发生了变化
  client:
    serviceUrl:
      defaultZone: ${eureka-url}  #注册到 EurekaServer

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: ALWAYS  #health endpoint是否必须显示全部细节
server:
  port: 8888
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      "user.name": admin         #These two are needed so that the server
      "user.password": admin #can access the protected client endpoints