feign:
  ma:
    rts_pubdata_server: http://10.10.10.117:8098/rts_pubdata_server
    rtmap-platform: https://dev.rtmap.com/rtmap-platform
    rtmap-app: http://10.10.11.166:8180/rtmap-app
    rtmap-coupon-web: http://10.10.11.166:8080/rtmap-coupon-web
    pay-api: http://pay.rtmap.com/pay-api
    mptools: http://10.10.11.146:8093
  crm:
    scrm-web-opr: http://211.157.182.226:8888/rtscrm/scrm-web-opr
spring:
  datasource:
    url: jdbc:mysql://10.10.11.47:3306/mini_apps?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    druid:
      username: rtmap
      password: rtmap911
  redis:
    host: 10.10.11.136
    port: 6379
    password: foobared